# Generated by Django 3.2.5 on 2021-07-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
