# Generated by Django 3.2.5 on 2021-07-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_apicall_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
