# Generated by Django 3.2.5 on 2021-07-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_apicalls_apicall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='date_posted',
        ),
    ]
