# Generated by Django 3.2.5 on 2021-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_apicall_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
